### ISSUE TITLE
Hardware docs?

### ISSUE THREAD

**Issue by samuk** [harsha-vk/weeder_bot#1]
Hi I was interested to see this repo. I'm also interested in weeding under ROS2. I've got some plans here: https://github.com/samuk/Sawppy_Rover/blob/main/modifications/Ag/readme.md

Is it worth collaborating on a common hardware platform?

Thanks

Sam

**Comment by harsha-vk** [comment]
My robot is a two wheeled differential robot. It has a camera, imu, gps. It sprays herbicide on weeds when detected
[like this](https://user-images.githubusercontent.com/51358498/152991630-fe343f37-5a45-43b0-900c-bb3cad4f1b80.JPG).

I don't know if this fits you as yours is a six wheeled one.

**Comment by samuk** [comment]
Hi, thanks for the reply. I guess the Nav/CV stuff may be similar, even if we're using quite different robots. I'm hoping to use Ubuntu 20.04/ Foxy, although the [install instructions](https://github.com/Agroecology-Lab/Headless-Jetson-Nano-Setup#readme) are untested as of now.

Are you working in crops or grassland? I saw you'd linked to[ ros_deep_learning](https://github.com/dusty-nv/ros_deep_learning/tree/431385d42ffb546d6aa5190154b6245e2854ff44) is that what you're planning to use for the CV? One of these [datasets](https://github.com/Agroecology-Lab/Open-Weeding-Delta#datasets) might be useful

Have you thought about your Nav strategy yet? Are you aiming to just use RTK? Bit of [discussion here](https://discourse.ros.org/t/navigation-for-precision-farming-in-open-fields/15138/14?u=samuk)

**Comment by harsha-vk** [comment]
I'm using foxy docker container from jetson containers.
Yes, I planned to use ros_deep_learning.
Currently I am focusing on hardware interface node. I'll look towards navigation after this.

**Comment by samuk** [comment]
Thanks, let's keep in touch on the Nav strategy stuff. Do you have a user on the [ROS Discourse?](https://discourse.ros.org/t/navigation-for-precision-farming-in-open-fields/15138/14) could we keep in touch there?

**Comment by harsha-vk** [comment]
Yes, let's keep in touch on the [ROS Discourse](https://discourse.ros.org/u/harsha-vk/summary).
